/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Pablo García
 */
public class frmMain extends javax.swing.JFrame {
    
    Random rnd = new Random();
    Hilo1 hilo1;
    Hilo2 hilo2;
    Hilo3 hilo3;

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SkeletonKing.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ghost.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mega_knight.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 240, 300));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CiclosB.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 220, 100));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CiclosC.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 110, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CiclosC.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 110, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CiclosC.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bv4F0o (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        hilo1 = new Hilo1();
        hilo2 = new Hilo2();
        hilo3 = new Hilo3();
        hilo1.start();
        hilo2.start();
        hilo3.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        hilo3.stop();
        if (jLabel2.getText() == jLabel3.getText() && jLabel2.getText() == jLabel4.getText()){
            
            Perdedor P = new Perdedor();
            P.setVisible(true);
        } else {
            
            Ganador G = new Ganador();
            G.setVisible(true);
        }
        
             
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        hilo2.stop();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       hilo1.stop();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public class Hilo1 extends Thread {
       
       
        @Override
        public void run(){
            
            int infinito = 0;
            while(infinito == 0){
            {
                int min = 1;
		int max = 3;
		int value = rnd.nextInt(3 + 1) + 1;
                
                if(value ==1){
                ImageIcon icon = new ImageIcon("C:\\Users\\Pablo García\\Documents\\GitHub\\casino-harvus1\\casino-harvus1\\src\\main\\java\\Imagenes\\SkeletonKing.png");
                jLabel2.setIcon(icon);
                
            
                try {
                    Thread.sleep(75);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                }
                
                            
                if(value ==2){
                ImageIcon icon = new ImageIcon("C:\\Users\\Pablo García\\Documents\\GitHub\\casino-harvus1\\casino-harvus1\\src\\main\\java\\Imagenes\\mega_knight.png");
                jLabel2.setIcon(icon);
                
            
                try {
                    Thread.sleep(75);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                }
               
                 if(value ==3){
                ImageIcon icon = new ImageIcon("C:\\Users\\Pablo García\\Documents\\GitHub\\casino-harvus1\\casino-harvus1\\src\\main\\java\\Imagenes\\Ghost.png");
                jLabel2.setIcon(icon);
                
            
                try {
                    Thread.sleep(75);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                }
                
                
            }
            
        }

        
    }
    }
    
    public class Hilo2 extends Thread {
       
       
        @Override
        public void run(){
            
            int infinito = 0;
            while(infinito == 0)
            {
                int min = 1;
		int max = 3;
		int value = rnd.nextInt(3 + 1) + 1;
                
            if(value ==1){
                ImageIcon icon = new ImageIcon("C:\\Users\\Pablo García\\Documents\\GitHub\\casino-harvus1\\casino-harvus1\\src\\main\\java\\Imagenes\\Ghost.png");
                jLabel3.setIcon(icon);
                
            
                try {
                    Thread.sleep(75);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                }
            
            if(value ==2){
                ImageIcon icon = new ImageIcon("C:\\Users\\Pablo García\\Documents\\GitHub\\casino-harvus1\\casino-harvus1\\src\\main\\java\\Imagenes\\SkeletonKing.png");
                jLabel3.setIcon(icon);
                
            
                try {
                    Thread.sleep(75);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                }
            
            if(value ==3){
                ImageIcon icon = new ImageIcon("C:\\Users\\Pablo García\\Documents\\GitHub\\casino-harvus1\\casino-harvus1\\src\\main\\java\\Imagenes\\mega_knight.png");
                jLabel3.setIcon(icon);
                
            
                try {
                    Thread.sleep(75);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                }
                
            }
            
        }

        
        }
    
    public class Hilo3 extends Thread {
       
       
        @Override
        public void run(){
            
            int infinito = 0;
            while(infinito == 0)
            {
                
                int min = 1;
		int max = 3;
		int value = rnd.nextInt(3 + 1) + 1;
                
                
                if(value ==1){
                ImageIcon icon = new ImageIcon("C:\\Users\\Pablo García\\Documents\\GitHub\\casino-harvus1\\casino-harvus1\\src\\main\\java\\Imagenes\\mega_knight.png");
                jLabel4.setIcon(icon);
                
            
                try {
                    Thread.sleep(75);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                }
                
                if(value ==2){
                ImageIcon icon = new ImageIcon("C:\\Users\\Pablo García\\Documents\\GitHub\\casino-harvus1\\casino-harvus1\\src\\main\\java\\Imagenes\\Ghost.png");
                jLabel4.setIcon(icon);
                
            
                try {
                    Thread.sleep(75);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                }
                
                if(value ==3){
                ImageIcon icon = new ImageIcon("C:\\Users\\Pablo García\\Documents\\GitHub\\casino-harvus1\\casino-harvus1\\src\\main\\java\\Imagenes\\SkeletonKing.png");
                jLabel4.setIcon(icon);
                
            
                try {
                    Thread.sleep(75);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
                }
            }
            
        }

        
        }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
